version: '3.7'

services:
  rabbit-user:
    image: rabbitmq:3.12.0-management
    hostname: rabbit-user
    container_name: rabbit-user
    ports:
      - 8085:15672
      - 5672:5672
    networks:
      - user
  redis:
    image: docker.io/redis:7.2.3
    container_name: redis
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - user
networks:
  user:
    driver: bridge